name: Refactoring
description: 리팩토링 관련 이슈 템플릿
title: "[Refactoring] "
labels: ["refactoring"]
body:
        - type: markdown
          attributes:
                value: |
                        기존 코드에 대한 리팩토링 시, 아래 항목을 작성해주세요.
        - type: textarea
          id: what-about
          attributes:
                label: 어떤 내용에 대한 수정인가요?
                description: 기존 코드의 동작과 문제점을 포함해 작성해주세요(스크린샷 등).
                placeholder: 예) /#2 에 작성된 코드에 layout shift가 발생하여 사용자 경험에 악영향을 미칩니다. 이를 개선하기 위해...
          validations:
                required: true
        - type: textarea
          id: how-to
          attributes:
                label: 관련 링크나 참고할 내용이 있다면 작성해주세요. (선택)
                placeholder: 예) https://www.notion.so/...
